import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const paytoneOne = localFont({
  src: "./fonts/PaytoneOne-Regular.ttf",
  variable: "--font-paytone-regular",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Baby Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={` ${paytoneOne.variable}`}>{children}</body>
    </html>
  );
}
